# Generated by Django 3.1 on 2020-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=50)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
    ]
